### ISSUE TITLE
[question] nbextension enable in post-link script?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/widgetsnbextension-feedstock#4]
Are we going to make people run the `jupyter nbextension enable --py widgetnbextension`, or do that in a post-install script?

We have been packaging our [stuff](https://github.com/Anaconda-Platform/nbpresent/blob/master/conda.recipe/post-link.sh) with this enabled:

```bash
# post-link.sh
"${PREFIX}/bin/jupyter-nbextension" enable nbpresent --py --sys-prefix
"${PREFIX}/bin/jupyter-serverextension" enable nbpresent --py --sys-prefix
```

This is still not ideal, as it makes it harder to put extensions in things like the Anaconda Distribution or other [Contructor](https://github.com/conda/constructor) products, but I feel it's a lot more reasonable for the user. For example, this handles the "multiple versions installed in different envs" case, etc.

Perhaps once we get `nbconfig.d` this can be entirely handled by just running the API commands in `build`, with the correct files ending up in `etc/jupyter`

**Comment by SylvainCorlay** [comment]
`post-link.sh` and `post-unlink.sh` are always picked up by conda?

**Comment by bollwyvl** [comment]
> `post-link.sh` and `post-unlink.sh` are always picked up by conda?

Right, and their `.bat` brethren. They will always work... aside from a few complications:
- when you do an `conda env update` of a new environment from an `environment.yml`, or `conda remove -n foo` the jupyter scripts might not be available. This is a known issue, and will eventually be fixed by topological sorting dependencies. But usually works. eek.
- as mentioned, post-link scripts don't fire for "standalone" distributions like anaconda. Unfortunately, because we're stuck with Jupyter's "one config to rule them all", which means a distribution distributor can only package one file... we're trying to make that happen for our [conda-specific stuff](https://github.com/ContinuumIO/anaconda-nb-extensions-meta-config), but want to include more things until we have the `conf.d` option... but have to get some more builds working.

**Comment by SylvainCorlay** [comment]
@bollwyvl Looking at the unlink.bat, it is different from the link.bat in that the `exe` extension is missing in nbpresent. Just FYI.
