### ISSUE TITLE
Migration plan for noarch and removing the link scripts

### ISSUE THREAD

**Issue by jasongrout** [conda-forge/widgetsnbextension-feedstock#52]
This migration plan is scattered among comments on several issues. I'm consolidating it here to have one reference place for this plan.

We'd like to eventually have this package be a noarch package. This requires us to remove the post link scripts. The post-link scripts are what automatically enable ipywidgets in notebook < 5.3, so removing them is basically telling people installing ipywidgets in notebook < 5.3 that they will have to run an extra command to enable the extension.

There are two timelines here:

1. The new conf.d approach was introduced in notebook 5.3, released in January 2018. I think we should give people about a year to upgrade, so I think we shouldn't remove the scripts before February 2019.
2. Before ipywidgets 7.3, the unlink script actively disabled the extension on uninstall. This means that if you upgrade from pre-7.3 directly to a release without a script, you actually end up with ipywidgets disabled. In ipywidgets 7.3, we changed the unlink script to properly uninstall the extension (instead of actively disabling it), so the smoothest upgrade path is for someone to upgrade to ipywidgets 7.3 or later that still has scripts, and *then* upgrade to the version without scripts. ipywidgets 7.3 came out July 2018. I think we should give people enough time to upgrade to 7.3 or later before removing the scripts, perhaps until July 2019?

*Edit: I think the other advice I have is that removing the link scripts is done on a version boundary of some kind, so that it's easier to communicate if things break (i.e., upgrade to version X to fix things, instead of trying to tell them to change a build number).*

For background conversation, see:

* https://github.com/conda-forge/widgetsnbextension-feedstock/pull/40 (lots of discussion about this, summarized above)
* https://github.com/conda-forge/widgetsnbextension-feedstock/pull/30
* https://github.com/conda-forge/widgetsnbextension-feedstock/pull/29
* https://github.com/conda-forge/widgetsnbextension-feedstock/pull/31
* https://github.com/conda-forge/widgetsnbextension-feedstock/pull/51

**Comment by maartenbreddels** [comment]
For reference, on windows 10, with a fresh anaconda install (as user, so I should not need admin rights), I get:
```
ERROR conda.core.link:_execute(507): An error occurred while installing package 'conda-forge::widgetsnbextension-3.4.2-py36_1000'.
PermissionError(13, 'Permission denied')
Attempting to roll back.
```

```
C:\Users\maartenbreddels>python
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.prefix
'C:\\Users\\maartenbreddels\\Anaconda3'
```
The command I was executing was:"
```
C:\Users\maartenbreddels>conda create -n vaex -c conda-forge jupyter  numpy scipy pyqt matplotlib pyopengl h5py numexpr astropy tornado cython pandas runipy cython pytest numba pyarrow>=0.12 -y
```

Not sure this is something we want to fix/debug, since the script will disappear this year.

**Comment by jasongrout** [comment]
We didn't end up removing this last year. Our deadlines above have passed a long time ago, so I think we should remove the scripts and switch to noarch in the next minor or major version.

**Comment by jasongrout** [comment]
I did this in the prerelease branch recipe: https://github.com/conda-forge/widgetsnbextension-feedstock/pull/58

**Comment by asford** [comment]
@jasongrout Is there a blocking factor on making this change to the package now (before the widgetsnbextension 4.x release series)? The use of this link script is now a long-pole in installations targeting jupyterlab with ipywidgets.

**Comment by jasongrout** [comment]
I think the only blocking factor at this point is the comment in the OP:

> Edit: I think the other advice I have is that removing the link scripts is done on a version boundary of some kind, so that it's easier to communicate if things break (i.e., upgrade to version X to fix things, instead of trying to tell them to change a build number).

At this point, we're more than a year past any upgrade window proposed in the OP, and with no immediate release planned in the near future, I think it's probably okay to just go for it in a build bump.

**Comment by jakirkham** [comment]
It's really cool seeing the resolution to this. Thanks all for pushing it forward! 😄
