### ISSUE TITLE
Can't get 4.0.11 version from pypi

### ISSUE THREAD

**Issue by mvp-v** [conda-forge/widgetsnbextension-feedstock#95]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Can't find 4.0.11 version while installing to JupyterLite:
```%pip install widgetsnbextension==4.0.11```
```
ValueError: Can't find a pure Python 3 wheel for 'widgetsnbextension~=4.0.11'.
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
You can use `await micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
```

```%pip install widgetsnbextension```
installs 4.0.10 version

### Installed packages

```shell
Pygments==2.16.1
asttokens==2.4.1
comm==0.2.2
decorator==5.1.1
executing==2.0.1
ipykernel==6.9.2
ipython==8.25.0
jedi==0.19.0
matplotlib-inline==0.1.7
micropip==0.5.0
packaging==23.1
parso==0.8.3
piplite==0.3.1
prompt-toolkit==3.0.45
pure-eval==0.2.2
pyodide-kernel==0.3.1
pyparsing==3.1.1
setuptools==68.1.2
six==1.16.0
stack-data==0.6.3
traitlets==5.14.3
typing-extensions==4.7.1
wcwidth==0.2.13
```

### Environment info

```shell
Environment is JupyterLite
https://jupyter.org/try-jupyter/lab/index.html
```

**Comment by bollwyvl** [comment]
Irrespective of not being a conda-forge problem, this has been solved by https://github.com/jupyterlite/pyodide-kernel/pull/111. 

As the specific versions might be cached, you may wish to try in a new private browsing window.
